### ISSUE TITLE
create-commit.sh has a hardcoded sha fro tree_sha and the ${json_file} is missing on lines 15 and 21

### ISSUE THREAD

**Issue by ricardojfc** [gm3dmo/the-power#112]
**Describe the bug**
`create-commit.sh` has a hardcoded sha fro tree_sha and the `${json_file}` variable is missing on lines 15 and 21

**To Reproduce**
Check lines 14, 15 and 21

**Expected behavior**
The tree sha shoudn't be hardcoded
On lines 15 and 21 you `${json}` should be `${json_file}`

**Comment by gm3dmo** [comment]
Given the create-commit.sh script does not work and is not used anywhere I have taken the cowards way out and removed it from The Power.

I added that file when I initially started on the power. It turns out creating commits is a multi step process you can see that demonstrated in:

 `run-testcase-tiny-app-code-signing` which calls:

```
tiny-app-codesign-create-a-commit.sh
tiny-app-codesign-create-a-tree.sh
tiny-app-codesign-update-a-reference.sh
```
